from core.entities.request_user import RequestUser
from core.repositories.user_repository import UserRepository
from core.use_cases.users.create_user import CreateUserUseCase
from core.use_cases.users.update_user_role import UpdateUserRoleUseCase
from core.use_cases.users.update_user_password import UpdateUserPasswordUseCase
from core.use_cases.users.toggle_user_active import ToggleUserActiveUseCase
from core.use_cases.users.update_user import UpdateUserUseCase
from core.use_cases.users.delete_user import DeleteUserUseCase
from typing import Optional